### PR TITLE
Fixed smithing crashes for "Tzikurion head" (2h axe), "Cataphracts Mace Head" & "Steel Horsemans Mace Handle" (2h mace)

### PR DESCRIPTION
**Pull request by ChrisF-127**
Smithing: fixed crash on selecting "Tzikurion head" (axe_craft_26_head) for two handed axes and "Cataphracts Mace Head" (mace_head_7) & "Steel Horsemans Mace Handle" (mace_handle_15) for two handed maces

Pretty sure I checked all blades, head pieces and handles for all weapons except for Daggers, didn't check pommels or guards (thoroughly) though

### CODE REVIEW

**Comment by JoeFwd** [comment]
Err it might be time to write a harmony patch to unlock all weapon pieces in the crafting menu just to check if the selection still crashes for some of them.

**Comment by ChrisF-127** [comment]
Just clicking through them when locked should work fine, I think, that's what I did.

An automatic testing method might be interesting, considering all the pommels and guards. Though I didn't look if this mod even adds or reuses any.

**Review by JoeFwd — CHANGES_REQUESTED** [review]
There is a missing comma at the end of mace_head_7

**Comment by ChrisF-127** [comment]
Fixed!
Sorry about that, I changed it in my game version but apparently forgot to fix it in the GitHub version.

**Review by JoeFwd — APPROVED** [review]

**Pull request merged**
